some updates for the case template

diff --git a/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/Allrun b/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/Allrun
--- a/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/Allrun
+++ b/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/Allrun
@@ -4,8 +4,25 @@
 # example of call: ./Allrun 3
 # First argument: number of processors to be used for calculation (Integer value)
 
+# Source tutorial run functions
+. $WM_PROJECT_DIR/bin/tools/RunFunctions
+
+ERROR_CODE=$?
+if [ $ERROR_CODE -ne 0 ]; then
+    echo -e "\nError:"
+    echo -e "OpenFOAM run functions not found\n" >&2
+    exit $ERROR_CODE
+fi
+
+application=$(getApplication)
+
 if [ ! -d "constant/polyMesh" ]; then
     ./preRun
+fi
+
+ERROR_CODE=$?
+if [ $ERROR_CODE -ne 0 ]; then
+    exit $ERROR_CODE
 fi
 
 if [ $1 -eq 1 ]; then
@@ -16,12 +33,19 @@ else
 
     ./decompose
 
+    ERROR_CODE=$?
+    if [ $ERROR_CODE -ne 0 ]; then
+        exit $ERROR_CODE
+    fi
+
     echo "Running $application in parallel on $PWD using $1 processes"
     mpirun -np $1 --output-filename log ./runApp $1 # > /dev/null 2>&1
 
     if [ $? -eq 0 ]; then
         ./reconstruct
 
-        rm -rf processor*
+        if [ $? -eq 0 ]; then
+            rm -rf processor*
+        fi
     fi
 fi
diff --git a/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/decompose b/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/decompose
--- a/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/decompose
+++ b/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/decompose
@@ -8,7 +8,7 @@ cd ${0%/*} || exit 1    # Run from this directory
 runApplication -overwrite decomposePar
 ERROR_CODE=$?
 if [ $ERROR_CODE -ne 0 ]; then
-    echo "\nError:"
-    echo "Domain decomposition failed! Check the corresponding log file.\n" >&2
+    echo -e "\nError:"
+    echo -e "Domain decomposition failed! Check the corresponding log file.\n" >&2
     exit $ERROR_CODE
 fi
diff --git a/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/makeMesh b/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/makeMesh
--- a/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/makeMesh
+++ b/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/makeMesh
@@ -7,7 +7,7 @@ cd ${0%/*} || exit 1    # Run from this directory
 unzip polyMesh.zip -d ./constant/polyMesh
 ERROR_CODE=$?
 if [ $ERROR_CODE -ne 0 ]; then
-    echo "\nError:"
-    echo "Mesh extraction failed!\n" >&2
+    echo -e "\nError:"
+    echo -e "Mesh extraction failed!\n" >&2
     exit $ERROR_CODE
 fi
diff --git a/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/preRun b/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/preRun
--- a/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/preRun
+++ b/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/preRun
@@ -7,6 +7,11 @@ cd ${0%/*} || exit 1    # Run from this directory
 
 ./makeMesh
 
+ERROR_CODE=$?
+if [ $ERROR_CODE -ne 0 ]; then
+    exit $ERROR_CODE
+fi
+
 set -x
 
 if [ ! -d "0.bkp" ]; then
@@ -21,23 +26,23 @@ fi
 runApplication -overwrite renumberMesh -overwrite
 ERROR_CODE=$?
 if [ $ERROR_CODE -ne 0 ]; then
-    echo "\nError:"
-    echo "renumberMesh failed! Check the corresponding log file.\n" >&2
+    echo -e "\nError:"
+    echo -e "renumberMesh failed! Check the corresponding log file.\n" >&2
     exit $ERROR_CODE
 fi
 
 # runApplication -overwrite topoSet
 # ERROR_CODE=$?
 # if [ $ERROR_CODE -ne 0 ]; then
-#     echo "\nError:"
-#     echo "topoSet failed! Check the corresponding log file.\n" >&2
+#     echo -e "\nError:"
+#     echo -e "topoSet failed! Check the corresponding log file.\n" >&2
 #     exit $ERROR_CODE
 # fi
 
 runApplication -overwrite setFields
 ERROR_CODE=$?
 if [ $ERROR_CODE -ne 0 ]; then
-    echo "\nError:"
-    echo "setFields failed! Check the corresponding log file.\n" >&2
+    echo -e "\nError:"
+    echo -e "setFields failed! Check the corresponding log file.\n" >&2
     exit $ERROR_CODE
 fi
diff --git a/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/runApp b/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/runApp
--- a/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/runApp
+++ b/osp/wrappers/wet_synthesis_wrappers/cases/precNMC/precNMC_foamTemplate/runApp
@@ -2,10 +2,17 @@
 cd ${0%/*} || exit 1    # Run from this directory
 
 # Add the required library path
-export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
+export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/sundials/instdir/lib
 
 # Source tutorial run functions
 . $WM_PROJECT_DIR/bin/tools/RunFunctions
+
+ERROR_CODE=$?
+if [ $ERROR_CODE -ne 0 ]; then
+    echo -e "\nError:"
+    echo -e "OpenFOAM run functions not found\n" >&2
+    exit $ERROR_CODE
+fi
 
 application=$(getApplication)
 
@@ -15,3 +22,9 @@ else
     $application -parallel
 fi
 
+ERROR_CODE=$?
+if [ $ERROR_CODE -ne 0 ]; then
+    echo -e "\nError:"
+    echo -e "$application failed\n" >&2
+    exit $ERROR_CODE
+fi
